### PR TITLE
`XDG_SESSION_TYPE` support

### LINKED ISSUE #92: X11 WM command fails due to X server never starting
This is similar to what was discussed in https://github.com/apognu/tuigreet/issues/15. Basically if my command is `startx` and the last line of my `.xinitrc` is the window manager exec (leftwm in my case) then it works, but if my command is directly `leftwm` it fails. What is the expected behavior/command for launching an X11 WM?

Looking at qtgreet it seems that this is the bit that creates an X11 session correctly:
```
bool GreetdLogin::startSession( QString baseCmd, QString type ) {
    /** Get the log name */
    QString logName = logPath + "/session/QtGreet-" + QDateTime::currentDateTime().toString( "ddMMyyyy-hhmmss" ) + ".log";

    QString cmd;

    if ( type == "wayland" ) {
        cmd = baseCmd + " > " + logName + " 2>&1";
    }

    else if ( type == "X11" ) {
        cmd = getX11Session( baseCmd ) + " > " + logName + " 2>&1";
    }

    else {
        cmd = baseCmd;
    }

    /** Send the start_session request */
    Response resp = startSession( cmd, prepareEnv() );

    if ( resp.responseType() == Response::Success ) {
        return true;
    }

    qDebug() << "Failed to launch the session:" << baseCmd;
    mErrorMsg = resp.errorMessage();
    resp      = cancelSession();

    if ( resp.responseType() != Response::Success ) {
        mErrorMsg += "\nError while handling the previous error. Abort.";
    }

    qDebug() << mErrorMsg;

    return false;
}
```
and
```
QString GreetdLogin::getX11Session( QString base ) {
    QString xinit( "xinit %1 -- %2 :%3 vt%4 -keeptty -noreset -novtswitch -auth %5/Xauth.%6" );

    /* Arg2: Get the display */
    int display;

    for ( display = 0; display < 64; display++ ) {
        QString x1 = QString( tmpPath + "/.X%1-lock" ).arg( display );
        QString x2 = QString( tmpPath + "/.X11-unix/X%1" ).arg( display );

        if ( QFile::exists( x1 ) or QFile::exists( x2 ) ) {
            continue;
        }

        else {
            break;
        }
    }

    /* Arg4: Random strings for server auth file */
    QString hash = QCryptographicHash::hash( QDateTime::currentDateTime().toString().toUtf8(), QCryptographicHash::Md5 ).toHex().left( 10 );

    return xinit.arg( base ).arg( xrcPath ).arg( display ).arg( vtNum ).arg( tmpPath ).arg( hash );
}

```
I will take a look at tuigreet's src to see if this can be added.

### PR DESCRIPTION
**Pull request by alebastr**
Detect session type, store it and send to the greetd daemon. Wrap X11 sessions with a command to initialize X server.

Fixes gnome-shell session startup on distributions with systemd (see https://todo.sr.ht/~kennylevinsen/greetd/15).
Fixes #92
Supersedes #74

### CODE REVIEW

**Comment by apognu** [comment]
I find this interesting, and as far as I can see reading the code, well-implemented. I am still unsure whether I want to have such specifics directly in the codebase, rather than leaving implementation details to the user, but I have to say, your pull request seems to alleviate some of my initial concerns.

I will test it out and try it with various X11 desktop environments to make sure it is abstract enough.

Being a bit rusty with X11, is `startx` consistently available whenever an X11 desktop environment is installed? Is it possible, since it is part of `xinit`, that `startx` isn't there? Just trying to cross out the Ts, it might be a reasonable assumption to make.

**Comment by alebastr** [comment]
> I will test it out and try it with various X11 desktop environments to make sure it is abstract enough.

There's at least one known issue: several places in the code use command to lookup the current session. GNOME uses the same desktop file with `Exec=/usr/bin/gnome-session` for X11 and Wayland, so whenever this lookup happens it picks the first available entry (usually `wayland`).
It's a preexisting problem, so I haven't touched that. But changing state format to `(desktop_name, session_type) | custom_command` should work.

> Being a bit rusty with X11, is `startx` consistently available whenever an X11 desktop environment is installed? Is it possible, since it is part of `xinit`, that `startx` isn't there? Just trying to cross out the Ts, it might be a reasonable assumption to make.

That is a valid concern, `xinit` and `startx` are optional and can be missing. On a pure Wayland system `xinit` also pulls in a few otherwise unused X11 dependencies (although nothing heavy).
If that bothers you, I can drop the default for the `--xsession-wrapper` option and leave `startx` as a suggestion in the docs.

**Comment by apognu** [comment]
I like the sane defaults that should work in "most standard" cases. And this is what this PR is about, have a sane default behavior for X11 sessions. So I do like having this. Maybe it would make more sense to provide a flag to _disable_ the automatic use of `startx` and rely entirely on the called script?

What do you think?

I still didn't have time to actually test this out, I hope I can this week.

**Comment by apognu** [comment]
> There's at least one known issue: several places in the code use command to lookup the current session.

Also, good catch. I will change the way this works.

**Comment by alebastr** [comment]
> I like the sane defaults that should work in "most standard" cases. And this is what this PR is about, have a sane default behavior for X11 sessions. So I do like having this. Maybe it would make more sense to provide a flag to _disable_ the automatic use of `startx` and rely entirely on the called script?
> 
> What do you think?

Do you mean adding `--no-xsession-wrapper` in addition to `--xsession-wrapper=<str>`? That makes sense. I'll add it.

**Comment by apognu** [comment]
Yes. I think having a way to disable the use of a wrapper script (or use a bare passthrough of `/usr/bin/env`) is a good idea. If only so people who use their own scripts that start X11 could still work.

People who have self-sufficient session scripts can still use them, and most people with standard distribution setups will get a working experience out of the box.

By the way, I took this PR for a test drive, and it works perfectly from my initial testing. I will start reviewing the code by tomorrow.

File: src/greeter.rs [hunk 1]
```diff
@@ -28,6 +30,11 @@ use crate::{
 
 const DEFAULT_LOCALE: Locale = Locale::en_US;
 const DEFAULT_ASTERISKS_CHAR: char = '*';
+lazy_static! {
+  // `startx` wants an absolute path to the executable as a first argument.
+  // We don't want to resolve the session command in the greeter though, so it should be additionally wrapped with a known noop command (like `/usr/bin/env`).
+  static ref DEFAULT_XSESSION_WRAPPER: Option<String> = which::which("env").ok().and_then(|p| p.to_str().map(|p| format!("startx {p}")));
```
Comment (alebastr) [inline src/greeter.rs:36]: This might be unnecessary; *most* of the sane systems are covered with a simple `"startx /bin/env"`.

Comment (apognu) [reply src/greeter.rs:36]: I would agree, I never met a system where `/bin/env` did not exist, and after all, this is why there is a flag that allows to override this behavior.

**Comment by apognu** [comment]
Okay, this should be good. I'll have a final go over tomorrow, and will merge if I don't find anything.

**Comment by apognu** [comment]
LGTM!

**Comment by bzm3r** [comment]
I just struggled with [this issue](https://todo.sr.ht/~kennylevinsen/greetd/15) + `tuigreet` today, because it seems that Gnome (currently?) does *not* find it sufficient to set `XDG_SESSION_TYPE=wayland`, and ultimately refuses to start up with errors in the journal like:

```
gnome-shell[907]: Failed to create backend: Could not get session ID: Session '1' is not a graphical session (type: 'tty')
systemd[853]: gnome-shell-wayland.service: Failed with result 'protocol'.
```

So, for me at least, the instructions in the README regarding Gnome currently do not work (and Google search results on the issue are also quite sparse!). I am using the main repository's package, not one from AUR, although I'm about to make that switch to solve this issue.

Given the relative seriousness of this issue (depending on how important it is for `tuigreet` to support Gnome, I suppose?) could an update to the main repo be pushed as well?

**Comment by apognu** [comment]
Could you open an issue, please?

Notably include your configuration (`tuigreet` command line) and the desktop file the session is picked up from so I can try and reproduce?
